### ISSUE TITLE
The menu and menuitem roles on the toggle toolbar are an improper use of ARIA

### ISSUE THREAD

**Issue by cannona** [joedolson/wp-accessibility#10]
This is not really a menu, at least not in the aria sense.  The ARIA standard is usually refering to pop-up menus when it uses this term.  In this case, all you have are a list of buttons that can be toggled, which is, IMHO, sufficiently conveyed via the current markup.

With the menu and menuitem roles, Jaws does not announce the pressed status of these buttons.  It just says that they are menu items, which is likely to be confusing to screen reader users, as they are expecting an entirely different interaction than what these buttons offer.

See https://www.w3.org/WAI/GL/wiki/Using_ARIA_menus for a sense of the sorts of things that these roles are properly used for.

**Comment by joedolson** [comment]
Thanks, Aaron - I'll get this in as soon as I can.
