### ISSUE TITLE
Edge crash - possible fix

### ISSUE THREAD

**Issue by tdoccc** [joedolson/wp-accessibility#13]
I noticed this when working on a second site using this plugin - I believe the reason Edge crashes is due to the pop-out yellow text (.offscreen) when hovering over the icon...

http://iwanttoconnect.co.uk/ If you look at this site, when the pop-out is disabled - it works ok.

I believe this is due to the css using clip-path... so an alternative may be required. Perhaps skew or a background-image?

(You might have already known about this but I thought I would let you know anyway - perhaps have an option to enable/disable the pop-out text?)

Ace plugin btw 👍  :)

**Comment by joedolson** [comment]
Thanks for following up on this - the Edge crash is pretty irritating. I'll explore whether the pop-out text is the cause of the issue. Thanks!

**Comment by joedolson** [comment]
Nope, that's not the issue - I can disable the entirety of the code for the pop-out and the crash still occurs. Thanks for the suggestion, but I'll have to stick with my existing solution for now!
