### ISSUE TITLE
current-menu-item

### ISSUE THREAD

**Issue by loopRW** [joedolson/wp-accessibility#15]
wp-accessibility/src/js/current-menu-item.js specifies the following rules:

```
$( '.current-menu-item' ).attr( 'aria-current', 'true' ).append( "<span class='screen-reader-text'>(current)</span>" );
$( '.current_page_item' ).attr( 'aria-current', 'true' ).append( "<span class='screen-reader-text'>(current)</span>" );
```
However, if an item has both **.current-menu-item** and **.current_page_item** classes, it gets appended twice.
Furthermore, the span is appended to **li** after **a** tag, while it should be inside the a tag. Otherwise, it gets read as a separate object. The following rule fixes this behavior:

`$( '.current-menu-item a, .current_page_item a' ).attr( 'aria-current', 'true' ).append( "<span class='screen-reader-text'>(current)</span>" );`

**Comment by joedolson** [comment]
Thanks for noting this! If you make a PR, I'll merge it. (If I don't hear from you fairly soon, I'll add it myself.)

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/wp-accessibility/commit/d856c22fc8793179ca0ef71b3a441d826942e97c
