### ISSUE TITLE
Conflict with NextGen gallery

### ISSUE THREAD

**Issue by netcreation** [joedolson/wp-accessibility#19]
If I have the NextGen gallery active, the toolbar will not work.

**Comment by BigBlackBibi** [comment]
Same here. 
I had put a lot of work into my NextGen galleries by the time I realized it messed up the Accessibility toolbar (toolbar stopped working), so I don't really want to change to a different gallery plugin, but then what?
Can you please look into this conflict issue?

**Comment by joedolson** [comment]
I've put some time into reviewing this, and it's...bizarre. NextGen breaks WP Accessibility's toolbar even when their JS isn't present, and I'm not sure why. This will take some significant exploration.

**Comment by joedolson** [comment]
Can no longer reproduce this, so I'm going to assume that it's no longer an issue. I may be wrong, but I never got anywhere in debugging it, so... :shrug:
