### ISSUE TITLE
Make WP Accessibility aware of Oxygen Builder

### ISSUE THREAD

**Issue by joedolson** [joedolson/wp-accessibility#22]
Oxygen Builder is a plug-in that disables theming, and should be treated as inaccessible regardless of the currently active theme's tags. See https://wordpress.org/support/topic/oxygen-builder-compatibility-3/

**Comment by wpmanagers** [comment]
> Oxygen Builder is a plug-in that disables theming, and should be treated as inaccessible regardless of the currently active theme's tags. See https://wordpress.org/support/topic/oxygen-builder-compatibility-3/

Can I ask if you have made any progress with working on this? I would love to use this plugin for oxygen builder accessibility and compliance.
