### ISSUE TITLE
Consider Adding AChecker TinyMCE Plugin

### ISSUE THREAD

**Issue by mrwweb** [joedolson/wp-accessibility#3]
I have no idea how feasible this is, but I wonder if adding the [AChecker plugin](http://www.atutor.ca/achecker/download.php) to TinyMCE might be an appropriate new feature for WP Accessibility.

I'd be potentially willing to try to work on this if it seems appropriate though that wouldn't happen until late August at the earliest.

**Comment by joedolson** [comment]
Go for it! It's a good idea; but I'm unlikely to get to it sooner than you will, with that time line.

**Comment by joedolson** [comment]
In all practicality, I don't think I'm going to be getting around to this. If you do get around to it, I'd encourage you to do it in a separate plug-in; I think that might be more appropriate.
