### ISSUE TITLE
Plugin crashed a WP website

### ISSUE THREAD

**Issue by Jetteroh** [joedolson/wp-accessibility#33]
**Describe the bug**
This plugin crashed our website

**To Reproduce - Error.log**
[17-Nov-2023 00:46:03 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function wpa_stats_title(), 1 passed in /home/xlberhu/xlber.hu/wp-includes/class-wp-hook.php on line 292 and exactly 2 expected in /home/xlberhu/xlber.hu/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php:584
Stack trace:
#0 /home/xlberhu/xlber.hu/wp-includes/class-wp-hook.php(292): wpa_stats_title('Bel\xC3\xA9p\xC3\xA9s/Regis...')
#1 /home/xlberhu/xlber.hu/wp-includes/plugin.php(212): WP_Hook->apply_filters('Bel\xC3\xA9p\xC3\xA9s/Regis...', Array)
#2 /home/xlberhu/xlber.hu/wp-content/themes/classter/includes/_wp_utils.php(1404): apply_filters('the_title', 'Bel\xC3\xA9p\xC3\xA9s/Regis...')
#3 /home/xlberhu/xlber.hu/wp-content/themes/classter/includes/_wp_utils.php(1278): getPostData(Array, NULL)
#4 /home/xlberhu/xlber.hu/wp-content/themes/classter/single.php(21): showPostLayout(Array)
#5 /home/xlberhu/xlber.hu/wp-includes/template.php(732): require('/home/xlberhu/x...')
#6 /home/xlberhu/xlber.hu/wp-includes/template.php(676): load_template('/home/x in /home/xlberhu/xlber.hu/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php on line 584

**Expected behavior**
Not to crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: LINUX - PHP
 - Browser Brave; Firefox

**Additional context**
Pls. test thoroughly the plugin before upload.

**Comment by joedolson** [comment]
This is technically a bug in your theme; it's not passing both variables to the `the_title` filter when calling it. It's pretty much reasonable to expect filters to have all passed variables available. 

I can handle the case, but it still could cause problems depending on the context where the theme is calling `apply_filters( 'the_title', 'callback' )`.  Those problems can only be resolved within the theme. The  hook `the_title` expects two arguments - a string and a post ID - and omitting one of those could create issues.

**Comment by Jetteroh** [comment]
Hi,
Thank you for trying to do something about it.
We have a paid WP theme, so I can't repair it.
Regards, Peter

Joe Dolson ***@***.***> ezt írta (időpont: 2023. nov. 17., P,
18:18):
