### ISSUE TITLE
Recurring Fatal Error thrown in wp-accessibility-stats.php file

### ISSUE THREAD

**Issue by pwnrod** [joedolson/wp-accessibility#34]
**Describe the bug**
Website throws a fatal error on line 100 of the wp-accessibility-stats.php file because the $test_old variable is sometimes null at that point. 

**To Reproduce**
Sorry, I don't know what exactly is triggering this error specifically. 

**Expected behavior**
I would expect the $test_old variable to be null checked before the timestamp property is set. 

**Screenshots**
I don't have a screenshot, but I can provide the error log information:

PHP Fatal error:  Uncaught Error: Attempt to assign property "timestamp" on null in /public_html/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php:100

Stack trace:
-0 /public_html/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php(225): wpa_add_stats()
-1 /public_html/wp-includes/class-wp-hook.php(324): wpa_stats_action()
-2 /public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
-3 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
-4 /public_html/wp-admin/admin-ajax.php(203): do_action()
-5 {main}
  thrown in /public_html/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php on line 100

**Desktop (please complete the following information):**
 N/A, not a front end bug. 

**Smartphone (please complete the following information):**
N/A, not a front end bug. 

**Additional context**
Happy to provide any additional information that could help resolve the issue. I appreciate the work put into this awesome plugin! Thanks for your time!

**Comment by joedolson** [comment]
I haven't been able to reproduce this in a live scenario, so I'm not sure exactly what's triggering it, but there are a lot of possible cases where json_encode could result in a null value, so it doesn't *really* matter why.

**Comment by joedolson** [comment]
Thanks for reporting the issue and providing all the details!
