### ISSUE TITLE
Your Site is Experiencing a Technical Issue Email to Admin with Error

### ISSUE THREAD

**Issue by primalspace** [joedolson/wp-accessibility#35]
Email received to admin upon login to WP admin area when the WP Accessibility plugin is enabled.

Subject: Your Site is Experiencing a Technical Issue

Email output as below:

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.5.3
Active theme: Theme Name (version 1.0.1) Current plugin: WP Accessibility (version 2.1.9) PHP version 8.3.7

Error Details
=============
An error of type E_ERROR was caused in line 375 of the file /var/www/vhosts/domain.com/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php. Error message: Uncaught ValueError: Unknown format specifier "a" in /var/www/vhosts/domain.com/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php:375
Stack trace:
#0 /var/www/vhosts/domain.com/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php(375): sprintf()
#1 /var/www/vhosts/domain.com/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php(294): wpa_stats_data_point()
#2 /var/www/vhosts/domain.com/wp-content/plugins/wp-accessibility/wp-accessibility-stats.php(258): wpa_get_stats()
#3 /var/www/vhosts/domain.com/wp-admin/includes/template.php(1456): wpa_dashboard_widget_stats_handler()
#4 /var/www/vhosts/domain.com/wp-admin/includes/dashboard.php(271): do_meta_boxes()
#5 /var/www/vhosts/domain.com/wp-admin/index.php(204): wp_dashboard()
#6 {main}
  thrown

**Comment by joedolson** [comment]
FYI, this is fixed in https://github.com/joedolson/wp-accessibility/commit/2dd73e78a3fd247b3461b3f31abb4d67a1199db8
