### ISSUE TITLE
Removing Image Doesn't Remove Longdesc Anchor

### ISSUE THREAD

**Issue by mrwweb** [joedolson/wp-accessibility#4]
In WordPress 4.2, removing an image that has a description and the associated anchor link from the plugin removes the image but not the anchor link.

I imagine two possible solutions:

1. Remove the anchor link when removing image html.
1. Switch from an anchor link to an ID on the image. (Does this have keyboard focus implications when users return to the page?) This also doesn't have any backwards compatibility for removing previously-inserted links.

**Comment by joedolson** [comment]
I assume you're referring to what happens in the visual editor? 

#1 is hypothetically doable, although it would require some complex scripting in TinyMCE to make the association between the link and the image. I don't know how to do this; but you're welcome to work on it, if you wish to contribute!

#2 isn't an option; removing the anchor link would break the access to the long description, unless I'm misunderstanding what you're referring to.

**Comment by mrwweb** [comment]
I should have clarified that I'm talking about when I'm using the "Browser Defaults Only" setting and yet there's still a link. Is that intended? Here's the HTML:

```html
<a href="http://localhost/wordpress/wp-content/uploads/2015/04/lost.jpg">
    <img class="aligncenter size-medium wp-image-6065" src="http://localhost/wordpress/wp-content/uploads/2015/04/lost-300x200.jpg" alt="Lego lost man" width="300" height="200" longdesc="http://localhost/wordpress?longdesc=6065&amp;referrer=6090" />
</a>
<a id="longdesc-return-6065"></a>
```

That last link is the one that threw me off. It looks to me like it's intended for the "Return to Article." link on the generated longdesc page. (Hence suggestion no. 2 above.) Is it used for some other reason too?

As for no. 1 above, your understanding of what's required is identical to mine. I'm pretty sure it's possible, but not really up for figuring it out right now :(

**Comment by joedolson** [comment]
Ah, yes - I see what you mean. You're right; that's intended as a return point, and probably could be replaced by an ID on the img itself. If you get to that soon, I'd appreciate a PR; if not, I can probably get to it relatively soon. Thanks!

**Comment by joedolson** [comment]
Resolving; updating in WP Accessibility 1.5.2
