### ISSUE TITLE
Regenerate a11y-toolbar fonts

### ISSUE THREAD

**Issue by XhmikosR** [joedolson/wp-accessibility#5]
Hi.

Can you regenerate the a11y-toolbar fonts so that we get woff2 support too?

**Comment by XhmikosR** [comment]
Hmmm, so after looking into it, it seems fontello doesn't offer woff2 [yet](https://github.com/fontello/fontello/issues/388).

**Comment by joedolson** [comment]
That would be an issue....I just contacted the guy who designed the icons originally about it; he may have another option.

**Comment by XhmikosR** [comment]
Font Awesome is available as woff2 too. Entypo, I don't think it is.

**Comment by XhmikosR** [comment]
But if the generator doesn't output woff2, I don't see any other way. Including the complete font files is an overkill.

**Comment by joedolson** [comment]
Chris is looking into it. Thanks! I'll reopen this if he's able to provide those.

**Comment by XhmikosR** [comment]
Thanks, but who's Chris?

**Comment by joedolson** [comment]
He designed the accessibility toolbar: https://github.com/clrux/a11y

**Comment by XhmikosR** [comment]
Damn, I missed this. I should have opened the request there :/

**Comment by joedolson** [comment]
Eh, that's fine. This is the primary place where the toolbar is being used, after all.

**Comment by XhmikosR** [comment]
I submitted a couple PRs upstream https://github.com/clrux/a11y/pulls/XhmikosR

**Comment by XhmikosR** [comment]
On a side note @joedolson, I see differences in the upstream code and the plugin code. For example your plugin is using `span`s instead of `i`'s for the icons.

**Comment by joedolson** [comment]
Yes, I have made changes (some fairly substantial) to the version being used here, so the two are not in synch.

**Comment by XhmikosR** [comment]
The specific change I mentioned breaks some stuff though, like https://github.com/joedolson/wp-accessibility/blob/master/toolbar/js/a11y.js#L59 since there's no longer an `i` element.

IMO you should do this more clear. Fork the upstream repo, make a custom branch with your changes on top and then use submodules.

**Comment by joedolson** [comment]
I actually don't do any of the development for WP Accessibility through Github at all; this is just a mirror of the SVN repository at WordPress.org.

**Comment by joedolson** [comment]
FYI, Chris has generated a new set of font icons including woff2 support. It may be a little while before I'm able to get this into the WordPress plug-in, because I'm leaving on vacation in a couple days, but I'll have it on my to do list.

**Comment by XhmikosR** [comment]
Yeah, I saw, but to be honest, I'm still struggling to see how you manage your custom changes. It's better for everyone to backport what we can backport upstream.

I'm working on improving the upstream dev process and submit a few patches.

**Comment by joedolson** [comment]
In order to integrate the toolbar into WordPress, I had to change some aspects in an incompatible way. Specifically, I had to take some hard-coded URLs and make them available through WordPress. Those changes can't be backported, because they would be meaningless in the context of the toolbar.

**Comment by XhmikosR** [comment]
Well, I'm talking about the selector names for example. Which is broken in your version like I mention [here](https://github.com/joedolson/wp-accessibility/issues/5#issuecomment-143812114) .

**Comment by XhmikosR** [comment]
@joedolson: any chance you make a new release with woff2 support?

**Comment by joedolson** [comment]
This will be in my next release. I'm not sure of a date; it'll either be late this week or the first week of February.

**Comment by XhmikosR** [comment]
@joedolson: please check https://github.com/joedolson/wp-accessibility/commit/7df6f6ff3908a570fc66a357b24456862744a822#commitcomment-15687095
